[project]
name = "fungame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pycryptodome>=3.23.0",
    "pyinstaller>=6.13.0",
    "pyqt5>=5.15.11",
    "pyuic5-tool>=0.0.1",
    "requests>=2.32.3",
]
